import cors from "cors";
import express, { NextFunction, Request, Response } from "express";
import * as admin from "firebase-admin";
import path from "path"; // Import path module

// Use require for JSON to ensure it's loaded correctly in CommonJS environment
const serviceAccountPath = path.resolve(__dirname, "../../ServiceAccountKey.json");
console.log("Resolved service account path:", serviceAccountPath); // Log the resolved path
const serviceAccount = require(serviceAccountPath);
console.log("Service account loaded:", !!serviceAccount); // Log if service account is loaded

// *** ADDED LOG START: Inspect full serviceAccount object ***
console.log("Full serviceAccount object before Admin SDK initialization:", serviceAccount);
// *** ADDED LOG END ***

import { createAnuncio, deleteAnuncio, getAnuncioById, getAnuncios, getAnunciosByUserId, updateAnuncio } from "./controllers/AnuncioController";
import { fetchUserData } from "./controllers/UserController";

const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Initialize Firebase Admin SDK if not already initialized
if (!admin.apps.length) {
  const credential = admin.credential.cert(serviceAccount as admin.ServiceAccount);
  console.log("Credential object generated by admin.credential.cert():", credential); // NEW LOG
  admin.initializeApp({
    credential: credential,
    projectId: serviceAccount.project_id, // Explicitly add project_id
  });
  console.log("Firebase Admin SDK initialized successfully");
} else {
  console.log("Firebase Admin SDK already initialized");
}

// *** ADDED LOGS START ***
console.log("Number of Firebase Admin SDK apps initialized:", admin.apps.length);
if (admin.apps.length > 0) {
  const defaultApp = admin.app();
  console.log("Default Firebase Admin SDK app name:", defaultApp.name);
  // Log a subset of options to avoid exposing sensitive keys in full
  console.log("Default Firebase Admin SDK app options (partial):", {
    projectId: defaultApp.options.projectId,
    credentialType: (defaultApp.options.credential as any)?.type, // Access type property of credential
    clientEmail: (defaultApp.options.credential as any)?.clientEmail,
  });
}
// *** ADDED LOGS END ***

// Initialize Firestore after the app has been initialized
const db = admin.firestore();

// Middleware to authenticate Firebase ID Token
interface AuthenticatedRequest extends Request {
  user?: admin.auth.DecodedIdToken;
}

const authenticate = async (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
  const authHeader = req.headers.authorization;
  console.log("Authorization Header:", authHeader); // ADDED LOG

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).send({ message: 'Unauthorized: No token provided' });
  }

  const idToken = authHeader.split('Bearer ')[1];
  console.log("Received ID Token:", idToken);
  console.log("Chegou aqui nessa murrinha!")

  try {
    const decodedToken = await admin.auth().verifyIdToken(idToken);
    req.user = decodedToken;
    console.log("Successfully decoded token for user:", decodedToken.uid);
    next();
  } catch (error) {
    console.error("Error verifying Firebase ID token:", error);
    return res.status(403).send({ message: 'Forbidden: Invalid token' });
  }
};

// RESTful API for Anuncios

// Create a new anuncio (requires authentication)
app.post("/anuncios", authenticate, async (req: AuthenticatedRequest, res: Response) => {
  console.log("Rota /anuncios chamada!");
  console.log("Usuário autenticado:", req.user?.uid);
  try {
    const { anuncioData } = req.body;
    const userId = req.user?.uid; // Get userId from authenticated user

    if (!anuncioData || !userId) {
      return res.status(400).send({ message: "Missing anuncioData or userId" });
    }
    const newAnuncio = await createAnuncio(db, anuncioData, userId);
    res.status(201).send(newAnuncio);
  } catch (error) {
    console.error("Error creating anuncio:", error);
    res.status(500).send({ message: "Error creating anuncio", error: error instanceof Error ? error.message : String(error) });
  }
});

// Get all anuncios (requires authentication)
app.get("/anuncios", authenticate, async (req, res) => {
  try {
    const searchQuery = req.query.q as string | undefined;
    console.log("Received request to get all anuncios with query:", searchQuery);
    const anuncios = await getAnuncios(db, searchQuery);
    res.status(200).send(anuncios);
  } catch (error) {
    console.error("Error getting anuncios:", error);
    res.status(500).send({ message: "Error getting anuncios", error: error instanceof Error ? error.message : String(error) });
  }
});

// Get a specific anuncio by ID
app.get("/anuncios/:id", async (req, res) => {
  try {
    const { id } = req.params;
    console.log("Received request for anuncio ID:", id);
    const anuncio = await getAnuncioById(db, id);
    if (anuncio) {
      console.log("Anuncio found in index.ts for ID:", id);
      res.status(200).send(anuncio);
    } else {
      console.log("Anuncio not found in index.ts for ID:", id);
      res.status(404).send({ message: "Anuncio not found" });
    }
  } catch (error) {
    console.error("Error getting anuncio by ID:", error);
    res.status(500).send({ message: "Error getting anuncio by ID", error: error instanceof Error ? error.message : String(error) });
  }
});

// Update an anuncio (requires authentication)
app.put("/anuncios/:id", authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { id } = req.params;
    const updatedData = req.body;
    const userId = req.user?.uid; // Get userId from authenticated user

    if (!updatedData || !userId) {
      return res.status(400).send({ message: "Missing updatedData or userId" });
    }
    // You might want to add logic here to ensure the authenticated user is the owner of the anuncio
    await updateAnuncio(db, id, updatedData);
    res.status(200).send({ message: "Anuncio updated successfully" });
  } catch (error) {
    console.error("Error updating anuncio:", error);
    res.status(500).send({ message: "Error updating anuncio", error: error instanceof Error ? error.message : String(error) });
  }
});

// Delete an anuncio (requires authentication)
app.delete("/anuncios/:id", authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { id } = req.params;
    const userId = req.user?.uid; // Get userId from authenticated user

    if (!userId) {
      return res.status(400).send({ message: "Missing userId from authenticated token" });
    }
    // You might want to add logic here to ensure the authenticated user is the owner of the anuncio
    await deleteAnuncio(db, id);
    res.status(200).send({ message: "Anuncio deleted successfully" });
  } catch (error) {
    console.error("Error deleting anuncio:", error);
    res.status(500).send({ message: "Error deleting anuncio", error: error instanceof Error ? error.message : String(error) });
  }
});

// Get anuncios by user ID (requires authentication)
app.get("/anuncios/user/:userId", authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { userId } = req.params;
    // Optional: Add a check to ensure req.user.uid === userId for security
    const anuncios = await getAnunciosByUserId(db, userId);
    res.status(200).send(anuncios);
  } catch (error) {
    console.error("Error getting anuncios by user ID:", error);
    res.status(500).send({ message: "Error getting anuncios by user ID", error: error instanceof Error ? error.message : String(error) });
  }
});

// RESTful API for User (requires authentication for fetching user data)

// Get user data by UID (requires authentication)
app.get("/users/:uid", authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { uid } = req.params;
    // Optional: Add a check to ensure req.user.uid === uid for security
    const userData = await fetchUserData(uid);
    if (userData) {
      res.status(200).send(userData);
    } else {
      res.status(404).send({ message: "User not found" });
    }
  } catch (error) {
    console.error("Error getting user data:", error);
    res.status(500).send({ message: "Error getting user data", error: error instanceof Error ? error.message : String(error) });
  }
});

app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
