import * as admin from "firebase-admin";
import path from "path";

// Ajuste o caminho para o seu ServiceAccountKey.json
const serviceAccountPath = path.resolve(__dirname, "../../ServiceAccountKey.json");
const serviceAccount = require(serviceAccountPath);

// *** ADDED LOG START: Inspect full serviceAccount object ***
console.log("Full serviceAccount object in verifyToken.ts before Admin SDK initialization:", serviceAccount);
// *** ADDED LOG END ***

// Inicializa o Admin SDK
if (!admin.apps.length) {
  const credential = admin.credential.cert(serviceAccount as admin.ServiceAccount);
  console.log("Credential object generated by admin.credential.cert() in verifyToken.ts:", credential); // NEW LOG
  admin.initializeApp({
    credential: credential,
    projectId: serviceAccount.project_id, // Explicitly add project_id for consistency
  });
}

// Cole aqui o token que você está recebendo no backend
const token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjlkMjEzMGZlZjAyNTg3ZmQ4ODYxODg2OTgyMjczNGVmNzZhMTExNjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZHNpLXZpdmEiLCJhdWQiOiJkc2ktdml2YSIsImF1dGhfdGltZSI6MTc2MDk4ODg5MiwidXNlcl9pZCI6IjJhM1NOR3RacVdObnB0c0NURzc3TDRmYUVlcjEiLCJzdWIiOiIyYTNTTkd0WnFXTm5wdHNDVEc3N0w0ZmFFZXIxIiwiaWF0IjoxNzYwOTg4ODkzLCJleHAiOjE3NjA5OTI0OTMsImVtYWlsIjoiYWpnczJAZGlzY2VudGUuaWZwZS5lZHUuYnIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWpnczJAZGlzY2VudGUuaWZwZS5lZHUuYnIiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.peM-2WdIgeQ1UsmhPZP-zoIqGFsFeE_L567l8kkj_J3pjnN2xSFLFiClIq3TC1dUR9_w19whRE7MoHcrZtWLDz2W-0x3yF8nPvw2OnFC8jM9gUE1xWKY4JLSicQjaiJ0IoGHSJecyLsv-XUwbzrHqQOUpu1Om9RD1qzKvSEDAckIJ-H6ZFfmn-QWv-5GMpWgJ_b4sCmxnDqE3lVvY1RRIv-58_kp_xhOw0nM6KONQBhIma3wsprF2CEOEd3JhypFs1fDzX0uR8QxbztpmSfIDgIWYQAz7QYYR70qpEeyqtXZdQJMHrFqJ4ef9jcOAYHksdIhYyvanPdKvTvOP4Ezuw";

async function verify() {
  try {
    const decoded = await admin.auth().verifyIdToken(token);
    console.log("Token válido! Decoded:", decoded);
  } catch (err) {
    console.error("Token inválido:", err);
  }
}

verify();
